import { HttpClient, HttpParams } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { FlagrService } from './features/flagr/flagr.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'angular-flagr-app';
  data$!: Observable<Response[]>;
  constructor(private client: HttpClient) {}

  ngOnInit(): void {
    let params: HttpParams = new HttpParams();
    // params.append('tags', 'ng-front-end,demo');
    params = params.append('tags', 'ng-front-end,demo');
    params = params.append('preload', true);
    this.data$ = this.client.get<Response[]>(
      'http://flagr.hypertheory-class.com/api/v1/flags?',
      { params }
    );
  }
}
// Generated by https://quicktype.io

export interface Response {
  dataRecordsEnabled: boolean;
  description: string;
  enabled: boolean;
  id: number;
  key: string;
  segments: any[];
  tags: Tag[];
  updatedAt: string;
  variants: any[];
}

export interface Tag {
  id: number;
  value: string;
}
